### ISSUE TITLE
看起来 imageList 是必须的吗？ 直接获取 img 的 src 不行？

### ISSUE THREAD

**Issue by ochukai** [xiecg/vue-fancybox#2]

**Comment by xiecg** [comment]
不行，需要一个`array`传递到`fancyBox`里面。

**Comment by ochukai** [comment]
这样的话 使用范围就很局限了~ 假如后台load出一篇文章，里面会有几张图片的话~这个就不适用了~ 要是能点击图片的时候根据 src 来显示大图就好了~  只是小建议~

**Comment by xiecg** [comment]
把文章的图片的放在一个`array`，传递给`fancyBox`。
然后html上的`img`就不要循环了，单个写吧，但是需要一些属性。下面是例子：

<img width="467" alt="qq20170517-161812 2x" src="https://cloud.githubusercontent.com/assets/10857932/26144682/652a522e-3b1c-11e7-9499-17ce9d8723e0.png">
