### ISSUE TITLE
What is the component-namespace in the fancyBox.vue

### ISSUE THREAD

**Issue by AkatQuas** [xiecg/vue-fancybox#3]
path: /src/fancyBox.vue
line 2: @component-namespace

this can not be resolved by the loaders, so the css won't work as it should.

Any comment on this one?

**Comment by xiecg** [comment]
需要 https://github.com/ElemeFE/postcss-salad 配合

**Comment by AkatQuas** [comment]
Well, I am trying to use fancy-box in vue.js project based on the webpack tempalte.
I have installed the loaders, and tried config the webpack.conf as following snippets, the file path is `build/vue-loader.conf.js`


    module.exports = {
       ...
    postcss: function () {
            return [ require('postcss-salad') ({
                features: { 'rem': false}
            })]
        }
    }
Things still not working.
Could you help me with that?

**Comment by xiecg** [comment]
The information provided is too little.

Try the documentation here https://github.com/ElemeFE/postcss-salad#webpack
