### ISSUE TITLE
IE 11 下报错

### ISSUE THREAD

**Issue by luguosheng1314** [xiecg/vue-fancybox#4]
运行demo  https://xiecg.github.io/other/vue-fancybox/#/baseUsage ，控制台抱错［缺少“:” build.js (16056:11)］

**Comment by mcwanderer** [comment]
我也遇到了这个问题，还以为是VUE2.0在IE11下的问题。后来发现官方例子在IE11也显示不正常。

**Comment by xiecg** [comment]
这个主要给移动端使用的。
